name: Custom Recovery Builder

on:
    workflow_dispatch:
        inputs:
            SELECTOR_RECOVERY:
                description: "Choose Custom Recovery Want's Build"
                required: true
                type: choice
                options:
                    - PBRP (android-12.1)
                    - TWRP (twrp-12.1)

jobs:
    Compile:
        name: Compiling ${{ inputs.SELECTOR_RECOVERY }}
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        
        # Steps Building
        steps:
            # Checkout
            - name: Check Out
              uses: actions/checkout@v4
            # Cleanup Dependencies
            - name: Cleanup Dependencies
              uses: rokibhasansagar/slimhub_actions@main
            # Setting Swap
            - name: Setting Swaps
              uses: pierotofy/set-swap-space@master
              with:
                swap-size-gb: 12
            # Upgrading And Updating Dependencies
            - name: Update And Upgrade Dependencies
              run: |
                sudo apt-get update
                sudo apt-get upgrade -y
            # Installing Dependencies
            - name: Installing Dependencies
              run: |
                sudo apt-get install repo bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y